# Generated by Django 4.0.5 on 2022-06-11 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_dev'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dev',
        ),
        migrations.DeleteModel(
            name='userr',
        ),
    ]
